### ISSUE TITLE
Compilation fails: string.h:51:20: error: expected ‘)’ before ‘VString

### ISSUE THREAD

**Issue by fbemm** [ruanjue/wtdbg#3]
I am trying to compile wtdbg and get the following error:

file_reader.c:247:8: note: include ‘<string.h>’ or provide a declaration of ‘strlen’
In file included from list.h:24:0,
                 from dmo.h:20,
                 from wtdbg.c:20:
./string.h:51:20: error: expected ‘)’ before ‘VString’
 define_list(VStrv, VString);
                    ^
In file included from list.h:24:0,
                 from dmo.h:20,
                 from wtdbg.c:20:
./string.h:245:71: error: unknown type name ‘VStrv’
 static inline string_size_t split_string(String *str, char separator, VStrv *vstrs){
                                                                       ^
./string.h:270:73: error: unknown type name ‘VStrv’
 static inline string_size_t split_vstring(VString *str, char separator, VStrv *vstrs, string_size_t cut){
                                                                         ^
In file included from dmo.h:20:0,
                 from wtdbg.c:20:

Additionally, there are thousand warning like this:

list.h:341:2: note: include ‘<string.h>’ or provide a declaration of ‘memcpy’
  memcpy(list1->buffer + list1->size, ary, sizeof(e_type) * size); \

Probably one should add `#include <string.h>` to all c files.

**Comment by ruanjue** [comment]
Which version of linux-gcc was used in you compilation? Or not linux-gcc. I tested the codes in linux-gcc 4.4.7.  Thanks for evaluation!

**Comment by fbemm** [comment]
I tried it with:

gcc (GCC) 4.8.4

and 

gcc (GCC) 5.4.0

**Comment by ruanjue** [comment]
I see, will update codes. Please wait for days.

**Comment by ruanjue** [comment]
Hi, please check out again. If there are still problems, please let me know. Thanks!

**Comment by fbemm** [comment]
Error still happens. I guess the code should be in a style that compiles on a current Ubuntu system with gcc (GCC) 4.8.4 or higher.

**Comment by fbemm** [comment]
./string.h:51:20: error: expected ‘)’ before ‘VString’
./string.h:245:71: error: unknown type name ‘VStrv’
./string.h:270:73: error: unknown type name ‘VStrv’
file_reader.h:63:2: error: unknown type name ‘VStrv’
file_reader.h:97:56: error: invalid type argument of ‘->’ (have ‘int’)
file_reader.h:97:56: error: invalid type argument of ‘->’ (have ‘int’)
file_reader.h:97:56: error: invalid type argument of ‘->’ (have ‘int’)

**Comment by ruanjue** [comment]
I have successfully compiled the latest code under Linux version 2.6.32-504.e16.x86_64, using GCC versions of gcc-4.4.7, gcc-4.9.4, gcc-5.4.0 and gcc-6.3.0.  BTW, my OS is redhat-release CentOS release 6.6.

**Comment by ruanjue** [comment]
If you are still having the problem, please see #4 .
