### ISSUE TITLE
GFA output of polished DBG

### ISSUE THREAD

**Issue by ekg** [ruanjue/wtdbg#5]
Would it be easy to add support for [GFAv1](https://github.com/GFA-spec/GFA-spec/blob/master/GFA1.md) output to wtdbg? I'd like to use the polished (and ideally compacted) DBG as input to another process and this would make it easy to do so.

**Comment by ruanjue** [comment]
I used to try to convert the output into GFA format, but hadn't finished it. I will find a time to complete the convertion, and update it.
