### ISSUE TITLE
about parameter -k

### ISSUE THREAD

**Issue by Xuelei-Dai** [ruanjue/wtdbg#6]
hello
I want to know how to determine the value of the parameter -k ?

**Comment by ruanjue** [comment]
-k 15 is suitable for PacBio RSII data in small genome. To assemble large genome, try -Hk 21. To assemble high error rate data, try -Hk 17/16/15. 
Fortunately, it is fast enough to test many parameters.

**Comment by Xuelei-Dai** [comment]
my genome size is about 700m,what is the boundary between a large genome and a small one?

**Comment by ruanjue** [comment]
700 Mb is relatively a small genome, -k 15 or -Hk 17 will be ok.

**Comment by Xuelei-Dai** [comment]
thanks,
If my genome has a high degree of heterozygosity, can I give some Suggestions on assembly, such as setting the -k parameter?

**Comment by ruanjue** [comment]
Believe me, it is fast enough to test different -k. Also, I recommend wtdbg-1.2.8 to you, it is more frequently maintained.
