### ISSUE TITLE
Recommendations for more sensitive overlaps?

### ISSUE THREAD

**Issue by mrvollger** [ruanjue/wtdbg#8]
Hi I am assembling a BAC (~200kbp) using pacbio data that has a large internal duplications (50 kbp) with some sequence differences. 

Do you have any suggestions for parameters I could adjust to make overlapping more sensitive/discerning between the two duplications?

Thanks!

**Comment by ruanjue** [comment]
If they differ much (I am not sure how much), try to use `-k 19 -Z 13`.

However, I am afraid it cannot distinguish large repeats by now. WTDBG and most other PacBio assemblers try to use long reads to cross the unique regions in both ends of repeats, but cannot phase repeats into independent copies. 

In fact, large duplications can be distinguished by carefully deal with the sequencing errors and SNV/INDELs, but now I haven't implemented it.

**Comment by mrvollger** [comment]
Thanks for the suggestion! Can you give me a brief description of each parameter, and whether increasing or decreasing them increases overlap specificity?

Yeah I am aware that pacbio assemblers struggle with this issue, so I know this is a little bit of a shot in the dark, but I figured I'd try some parameter tuning before giving up. 

Thanks again!

**Comment by ruanjue** [comment]
Please have a look at https://github.com/ruanjue/wtdbg-1.2.8, `wtdbg-1.2.8 --help` will give you instructions.

If you insist to use wtdbg-1.1.005, please tune the -k, -S, -m, and -Z.

**Comment by mrvollger** [comment]
Opp, I didn't realize I was commenting on an old release, I am using wtdbg-1.2.8. 
Thanks for your help!
