### ISSUE TITLE
Scaffolding suggestions

### ISSUE THREAD

**Issue by githubgig** [ruanjue/wtdbg#9]
Hello,

I used wtdbg to build contigs using Pacbio reads. Do you recommend any particular tools for scaffolding?

Thanks.

**Comment by ruanjue** [comment]
Please try LRScaf. Qin, Mao, et al. “LRScaf: Improving Draft Genomes Using Long Noisy Reads.” BMC Genomics, vol. 20, no. 1, 2019, pp. 1–12.

**Comment by githubgig** [comment]
Thank you.
